str_path_base = 'first_soltuions_set/';
% % str_file_list = {'lambda_v-2.987500e-03.sol', ...
%                     'lambda_v-5.050000e-03.sol',...
%                     'lambda_v-5.462500e-03.sol', ...
%                     'lambda_v-8.762500e-03.sol', ...
%                     'lambda_v-9.250000e-04.sol', ...,
%                     'solution_v1.sol'};
str_file_list = {'solution_Sp_01_11_20.sol', ...
                 'lambda_v-9.210526e-04.sol', ...
                 'lambda_v-9.736842e-04.sol'}

dim_list = size(str_file_list);
dim = dim_list(2);
ls = {'k-', 'r--', 'b-.', 'k:','r-'};
labels = {'S(t)', 'E(t)', 'I_S(t)', ...
                'I_A(t)', 'R(t)', 'D(t)' ...
                'V(t)', 'Coverage', 'Cost'};
figure(1)
for i = 1:dim
    path = strcat(str_path_base, char(str_file_list(i)));
    disp(path);
    
    verbose = 1;
    [dim_state, dim_control, ...
        dim_algebraic, dim_optimvars, dim_constant, ...
        dim_boundarycond, dim_pathcond, time_steps, ...
        time, stage, state, control, control_average, ... 
        algebraic, constants, optimvars, ...
        state_lb, state_ub, control_lb, control_ub, ...
        boundarycond, boundarycond_lb, boundarycond_ub, ...
        path_constraint, pathcond_lb, pathcond_ub, ...
        dynamic_constraint, ...
        adjoint, pathconstraint_mult, ...
        zl_state, zu_state, zl_control, zu_control,...
        objective, constraints_Infnorm, ...
        iterations] = readsolfile(path, verbose);

    cHeader = {'time', ...
                's','e','i_s','i_a', ...
                'r','d','v','x_vac_counter', ... 
                'cost', 'control'};
    commaHeader = [cHeader; repmat({','}, 1, numel(cHeader))];
    commaHeader = commaHeader(:)'; 
    textHeader = cell2mat(commaHeader);
    textHeader = textHeader(1:end - 1);
    %write header to file
    file_name = strcat(path, '.csv');
    disp(file_name)
    fid = fopen(file_name,'w'); 
    fprintf(fid,'%s\n',textHeader);
    fclose(fid);
    data = cat(2, time(2:end), state(2:end, :), control);
    %write data to end of file
    dlmwrite(file_name ,data,'-append', 'precision', 16);
   
    %
    for j=1:9
        subplot(3, 4, j)
        hold on
        xlabel('t')
        ylabel(char(labels(j)))
        plot(time, state(:, j), char(ls(i)))
        point = [time(end), state(end, j)];
        hold on
        plot([point(1), point(1)], [0, point(2)], char(ls(i)))
    end
    subplot(3, 4 , [10 11 12])
    hold on
    xlabel('t')
    ylabel('u(t)')
    plot(time(2:end), control, char(ls(i)))
    hold on
    lagend_input ={'2.987500e-03', ...
                    '5.050000e-03',...
                    '5.462500e-03', ...
                    '8.762500e-03', ...
                    '9.250000e-04'};
    
                
end
lgd = legend(lagend_input, 'Location','bestoutside');
title(lgd,'max lambda_v');
saveas(gcf,'fig_vaccination.pdf')
